name: Deploy PR
on: [ pull_request_review_comment, issue_comment ]
jobs:
  check_comment:
    name: Check comment
    runs-on: ubuntu-20.04
    steps:
      - name: Check comment
        run: |-
          echo ISSUE COMMENTED AT $(date)
      - name: Check if keyword
        id: keyword
        run: |-
          COMMENT=$(jq .comment.body $GITHUB_EVENT_PATH)
          if [ "x$COMMENT" = "x" ]; then
            echo ::set-output name=match::true
          else
            echo ::set-output name=match::false
          fi
      - name: Continue deploy
        if: steps.keyword.outputs.match
        run: echo "CONTINUE DEPLOY"
