name: Deploy PR
on: [ pull_request_review_comment, issue_comment ]
jobs:
  check_comment:
    name: Check comment
    runs-on: ubuntu-20.04
    steps:
      - name: Check comment
        run: |-
          echo ISSUE COMMENTED AT $(date)

      - name: Event action check
        id: eventcheck
        run: |-
          EVENT_ACTION=$(jq -r .action $GITHUB_EVENT_PATH)

          if [ "x$EVENT_ACTION" = "xcreated" ]; then
            echo ::set-output name=created::true
          fi

      - name: Check for keyword
        if: steps.eventcheck.outputs.created
        id: keyword
        run: |-
          COMMENT=$(jq -r .comment.body $GITHUB_EVENT_PATH)

          if [ "x$COMMENT" = "xREVIEW" ]; then
            echo ::set-output name=match::true
          fi

      - name: DEBUG
        run: echo ${{ steps.keyword.outputs.match }}

      - name: Continue deploy
        if: steps.keyword.outputs.match
        run: echo "CONTINUE DEPLOY"
      
      - name: Extract comments URL
        id: commentsurl
        if: steps.keyword.outputs.match
        run: |-
          COMMENTS_URL=$(jq -r .issue.comments_url $GITHUB_EVENT_PATH)
          echo ::set-output name=url::$COMMENTS_URL

      - name: Deployment notification
        if: steps.commentsurl.outputs.url
        run: |-
          curl -X POST \
            -H "Authorization: token ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            ${{ steps.commentsurl.outputs.url }} \
            --data '{"body": "Released to ...."}'


      
