name: Deploy PR
on:
  workflow_dispatch:
  pull_request_review:
  pull_request_review_comment:
jobs:
  check_comment:
    name: Check comment
    runs-on: ubuntu-20.04
    steps:
      - name: Check comment
        run: |-
          echo Hello world
