name: Deploy PR
on: [ issue_comment ]
jobs:
  check_comment:
    name: Check comment
    runs-on: ubuntu-20.04
    steps:
      - name: Check comment
        run: |-
          echo ISSUE COMMENTED AT $(date)
      - name: debug data
        run: |-
          echo "$GITHUB_EVENT_PATH"
