name: Deploy PR
on: [ pull_request_review_comment, issue_comment ]
jobs:
  check_comment:
    name: Check comment
    runs-on: ubuntu-20.04
    steps:
      - name: Check comment
        run: |-
          echo ISSUE COMMENTED AT $(date)
      - name: Check if keyword
        id: keyword
        run: |-
          COMMENT=$(jq .comment.body $GITHUB_EVENT_PATH)

          echo "FOUND $COMMENT"

          if [ "x$COMMENT" = 'x"$REVIEW"' ]; then
            echo ::set-output name=match::true
          fi
      - name: DEBUG
        run: echo ${{ steps.keyword.outputs.match }}
      - name: Continue deploy
        if: steps.keyword.outputs.match
        run: echo "CONTINUE DEPLOY"
