name: Deploy PR
on:
  workflow_dispatch:
  issue_comment:
  pull_request_review:
    types: [submitted, edited]
  pull_request_review_comment:
jobs:
  check_comment:
    name: Check comment
    runs-on: ubuntu-20.04
    steps:
      - name: Check comment
        run: |-
          echo WITH COMMENT AT $(date)
