name: Deploy PR
on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted, edited]
jobs:
  check_comment:
    name: Check comment
    runs-on: ubuntu-20.04
    steps:
      - name: Check comment
        run: |-
          echo Hello world again
